USE BOT
GO

--INSERT ACERVO
INSERT INTO ACERVO VALUES ('Hayashida, Alex Seiiti','Data webhouse aplicado a sites da internet','Sérgio Furgeri','2011-11-01',GETDATE())
INSERT INTO ACERVO VALUES ('Abrili, Everton da Conceição','A adequação da entrega na cadeia logística para uma empresa de pequeno porte na cidade de Indaiatuba','Arthur Silva Filho','2009-07-01',GETDATE())
INSERT INTO ACERVO VALUES ('Pereira, Sheila Nilma','A aplicação do scrum buscando a viabilização da comunicação em projetos de desenvolvimento de software','Ricardo Slavov','2009-07-01',GETDATE())
INSERT INTO ACERVO VALUES ('Moura, Walter Edson de','A dificuldade de acesso do menor de rua à tecnolgia de informação','Silma Carneiro Pompeu','2002-12-01',GETDATE())
INSERT INTO ACERVO VALUES ('Silva, Tamires Freire','A estrada de ferro Santos-Jundiaí e as exportações jundiaienses','Reinaldo Toso Jr.','2010-07-01',GETDATE())
INSERT INTO ACERVO VALUES ('Hass, Débora','A evolução do transporte áreo de cargas no Brasil','Benedito Carlos Florêncio Silva','2000-11-01',GETDATE())
INSERT INTO ACERVO VALUES ('Leite, Daniel de Campos','A excelência no atendimento ao cliente como diferencial competitivo','Paulo Roberto Nunes Fortaleza','2009-12-01',GETDATE())
INSERT INTO ACERVO VALUES ('Vidal, Vinicius Barros','A exportação brasileira de serviços na área de tecnologia da informação e o Siscoserv','João Manoel de Campos','2016-12-01',GETDATE())
INSERT INTO ACERVO VALUES ('Bezzan, Mayara Melo','A importância do modal ferroviário na inserção internacional da região metropolitana de Campinas','Ricardo Neiva Nóbrega','2009-12-01',GETDATE())
INSERT INTO ACERVO VALUES ('Oliveira, Cinthia Thais de','Análise de crédito e financiamento oferecidos às PMEs da cidade de Indaituba','Vilma Maria Lima','2011-11-01',GETDATE())
INSERT INTO ACERVO VALUES ('Oliveira, Giovana Fadini de','Aplicação de ferramenta de mineração de dados Tanagra nos registros de frequência dos professores da secretaria municipal de educação do município de Indaiatuba','Maria das Graças Junqueira Machado Tomazela','2008-06-01',GETDATE())
INSERT INTO ACERVO VALUES ('Almeida, Gabriel Santos de','Aplicação de processo de descoberta de conhecimento utilizando dados de cana-de-açúcar de uma usina do estado de São Paulo','Maria das Graças J. M. Tomazela','2012-11-01',GETDATE())
INSERT INTO ACERVO VALUES ('Lima, Joana D arc de','As ferramentas da qualidade e a sua aplicabilidade na resolução de distorção no controle de estoques','Benedito Carlos Florêncio Silva','2015-12-01',GETDATE())
INSERT INTO ACERVO VALUES ('Bigatto, Karen Alves','Auto-estima : como ser mais feliz nesse mundo louco','Cristina Arantes Raugi','1999-11-01',GETDATE())
INSERT INTO ACERVO VALUES ('Lui, Aline Maria','Auto-estima : um fator importante para o sucesso','Eugenio Tadeu Bertagnoli','2000-11-01',GETDATE())
INSERT INTO ACERVO VALUES ('Barros, Valério Silveira','Coaching : O método que desenvolve pessoas','Maurício Dias','2002-11-01',GETDATE())
INSERT INTO ACERVO VALUES ('Di Benedetto, Fernanda Izidia','Comércio exterior: A importância do conhecimento dos aspectos culturais de um país nas negociações internacionais','Sandro Roberto Silva Calabrezi ','2009-07-01',GETDATE())
INSERT INTO ACERVO VALUES ('Pansonato, Ramon','Comparação dos algoritmos k-means e fuzzy c-means, em dados do censo varietal qualitativo da cana-de-açúcar de uma usina do estado de São Paulo.','Maria das Graças Junqueira Machado Tomazela','2012-11-01',GETDATE())
INSERT INTO ACERVO VALUES ('Pacheco, Andréia Dias','Comunicação interna: uma análise na Indemental Gráficos ltda.','Virgílio Itaiuti Panzetti','2008-12-01',GETDATE())
INSERT INTO ACERVO VALUES ('Carozzi, Caroline Maria Costa','"Atalhos" na introdução de sistemas de gestão da qualidade',' Silma Carneiro Pompeu','2005-12-01',GETDATE())
INSERT INTO ACERVO VALUES ('Rossi, Angelita','Criatividade','Eugenio Tadeu Bertagnoli','2000-11-01',GETDATE())
INSERT INTO ACERVO VALUES ('Lima, Flávio Franco de','Criatividade: Como manter um ambiente criativo em sua empresa','Antônio Claret Culhari','2001-11-01',GETDATE())
INSERT INTO ACERVO VALUES ('Matos, Juliana Rodrigues de','Criatividade: Um diferencial competitivo','Eugênio Tadeu Bertagnoli','2008-06-01',GETDATE())
INSERT INTO ACERVO VALUES ('Sonego, Daiane','Data warehouse como facilitador na tomada de decisões','Wilson José de Oliveira','2008-11-01',GETDATE())
INSERT INTO ACERVO VALUES ('Silva Júnior, Carlos Alberto Gomes da','Desenvolvimento de um sistema mini ERP acadêmico para a Fatec Indaiatuba','Ricardo Roberto Leme','2009-06-01',GETDATE())
INSERT INTO ACERVO VALUES ('Silva, Tatiane da','Empreendedorismo de uma empresa familiar','Reinaldo Toso Júnior','2009-07-01',GETDATE())
INSERT INTO ACERVO VALUES ('Souza, Cristiane Martins de','Empregabilidade : Novos tempos para o profissional','Eugênio Tadeu Bertagnoli','1999-12-01',GETDATE())
INSERT INTO ACERVO VALUES ('Sette, Sandra Regina Ferreira','Estratégias de comunicação através do marketing direto','Devancyr Souza Dias','2009-12-01',GETDATE())
INSERT INTO ACERVO VALUES ('Santos, Daniela Rafael dos','Estudando a importância da gestão da marca : marca Correios, tão antiga quanto o Brasil!','Eugênio Tadeu Bertagnoli','2009-07-01',GETDATE())
INSERT INTO ACERVO VALUES ('Salvador, Artur Persichitti Porto','A acuracidade de estoque em uma empresa X','Carlos Fragoso','2016-12-01',GETDATE())
INSERT INTO ACERVO VALUES ('Buzo, Efraim da Silva','Agendamento digital para serviços de Pet Shop','Janaine Cristiane de Souza Arantes','2016-07-01',GETDATE())
INSERT INTO ACERVO VALUES ('Silva, Ana Paula Pereira da','Agendamento digital para serviços de Pet Shop','José Estanislau Sigrist','2014-12-01',GETDATE())

