USE BOT
GO

-- INSERT Progresso
INSERT INTO Progresso VALUES ('CAD_INICIO')
INSERT INTO Progresso VALUES ('CAD_INICIO_NEG')
INSERT INTO Progresso VALUES ('CAD_UNI')
INSERT INTO Progresso VALUES ('CAD_UNI_NEG')
INSERT INTO Progresso VALUES ('CAD_RES_UNI')
INSERT INTO Progresso VALUES ('CAD_RES_UNI_NEG')
INSERT INTO Progresso VALUES ('CAD_RES_UNI_NEG_LISTA')
INSERT INTO Progresso VALUES ('CAD_CURSO')
INSERT INTO Progresso VALUES ('CAD_CURSO_NEG')
INSERT INTO Progresso VALUES ('CAD_CURSO_RESP')
INSERT INTO Progresso VALUES ('CAD_CURSO_RESP_NEG')
INSERT INTO Progresso VALUES ('CAD_FIM')
INSERT INTO Progresso VALUES ('CAD_ERRO')
INSERT INTO Progresso VALUES ('NEG')
INSERT INTO Progresso VALUES ('CONF')
INSERT INTO Progresso VALUES ('CAD_TERMO')
INSERT INTO Progresso VALUES ('PES_RES_NEG')


select * from Progresso ORDER BY ID
