USE BOT
GO

-- INSERT Mensagem_Dominio
INSERT INTO Mensagem_Dominio VALUES (1,'Oi {nome}, percebi que é novo por aqui, gostaria de conhecer mais sobre você! Pode me ajudar?(S/N)',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (1,'Bem vindo(a) {nome}! Estou aqui para te ajudar, mas antes, gostaria de te conhecer um pouco mais, pode me ajudar?(S/N)',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (1,'Olá {nome}, espero que esteja bem! Percebi que é novo por aqui, estou aqui para te ajudar! Mas antes, posso conhecer um pouco sobre você?(S/N)',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (2,'Ahh tudo bem, então até a próxima!',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (2,'Tudo bem, até a próxima então!',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (3,'Ahh que bom, de qual FATEC você é?',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (3,'Maravilha!! Você está em qual FATEC hoje?',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (3,'Ótimo!! De qual FATEC você é?',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (4,'OK, então qual é?',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (5,'Ahh você está falando da {universidade}?(S/N)',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (5,'Então você é da {universidade}?(S/N)',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (5,'Hmm você quis dizer {universidade}?(S/N)',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (6,'Desculpa, não entendi direito.Qual FATEC você é?',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (6,'Desculpa, errar é humano né? Qual FATEC você é ?',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (6,'Acho que não entendi direito, pode me dizer o nome da FATEC novamente?',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (7,'Bom, não me lembro muito bem dessa FATEC, até o momento eu conheço essas, me diga se é uma delas...',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (8,'Agora ficou bem claro rsrs e qual curso você está cursando nela?',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (8,'Entendi, entendi, e qual curso você está cursando nela?',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (9,'Nunca ouvi falar desse curso, de qual curso você é?',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (9,'Não conheço esse curso ainda, pode me dizer novamente?',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (10,'Então você cursa {curso}?(S/N)',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (10,'Ahh então você está fazendo {curso}?(S/N)',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (11,'Foi mal, acho que não entendi muito bem, pode me dizer denovo por favor?',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (11,'Não? Desculpa, então talvez eu não tenha entendido direito... Pode me dizer novamente?',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (12,'Legal!! Agora te conheço um pouco melhor, então estou disponível para te ajudar!',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (12,'Bacana, bom, agora que eu te conheço um pouco mais, estou aqui para te ajudar quando for preciso!',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (13,'No momento estou ocupado, pode tentar novamente mais tarde?',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (13,'Estou indisponível no momento, pode falar comigo mais tarde por favor?',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (14,'não',GETDATE(),GETDATE(),8)
INSERT INTO Mensagem_Dominio VALUES (14,'nao',GETDATE(),GETDATE(),8)
INSERT INTO Mensagem_Dominio VALUES (14,'n',GETDATE(),GETDATE(),8)
INSERT INTO Mensagem_Dominio VALUES (14,'nn',GETDATE(),GETDATE(),8)
INSERT INTO Mensagem_Dominio VALUES (14,'nop',GETDATE(),GETDATE(),8)
INSERT INTO Mensagem_Dominio VALUES (14,'np',GETDATE(),GETDATE(),8)
INSERT INTO Mensagem_Dominio VALUES (14,'ao',GETDATE(),GETDATE(),8)
INSERT INTO Mensagem_Dominio VALUES (14,'no',GETDATE(),GETDATE(),8)
INSERT INTO Mensagem_Dominio VALUES (14,'na',GETDATE(),GETDATE(),8)
INSERT INTO Mensagem_Dominio VALUES (14,'nah',GETDATE(),GETDATE(),8)
INSERT INTO Mensagem_Dominio VALUES (14,'nã',GETDATE(),GETDATE(),8)
INSERT INTO Mensagem_Dominio VALUES (14,'ão',GETDATE(),GETDATE(),8)
INSERT INTO Mensagem_Dominio VALUES (14,'negativo',GETDATE(),GETDATE(),8)
INSERT INTO Mensagem_Dominio VALUES (15,'sim',GETDATE(),GETDATE(),9)
INSERT INTO Mensagem_Dominio VALUES (15,'ss',GETDATE(),GETDATE(),9)
INSERT INTO Mensagem_Dominio VALUES (15,'s',GETDATE(),GETDATE(),9)
INSERT INTO Mensagem_Dominio VALUES (15,'é',GETDATE(),GETDATE(),9)
INSERT INTO Mensagem_Dominio VALUES (15,'e',GETDATE(),GETDATE(),9)
INSERT INTO Mensagem_Dominio VALUES (15,'eh',GETDATE(),GETDATE(),9)
INSERT INTO Mensagem_Dominio VALUES (15,'éh',GETDATE(),GETDATE(),9)
INSERT INTO Mensagem_Dominio VALUES (15,'aham',GETDATE(),GETDATE(),9)
INSERT INTO Mensagem_Dominio VALUES (15,'positivo',GETDATE(),GETDATE(),9)
INSERT INTO Mensagem_Dominio VALUES (15,'exato',GETDATE(),GETDATE(),9)
INSERT INTO Mensagem_Dominio VALUES (15,'com certeza',GETDATE(),GETDATE(),9)
INSERT INTO Mensagem_Dominio VALUES (15,'ok',GETDATE(),GETDATE(),9)
INSERT INTO Mensagem_Dominio VALUES (15,'beleza',GETDATE(),GETDATE(),9)
INSERT INTO Mensagem_Dominio VALUES (15,'okey',GETDATE(),GETDATE(),9)
INSERT INTO Mensagem_Dominio VALUES (15,'blz',GETDATE(),GETDATE(),9)
INSERT INTO Mensagem_Dominio VALUES (16,'Você permite que todas as suas informações sejam armazenadas e utilizadas para a melhoria do aplicativo?(S/N)',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (17,'Que pena, não encontrei nada, tente novamente!',GETDATE(),GETDATE(),4)
INSERT INTO Mensagem_Dominio VALUES (17,'Oi ainda não entendi o que precisa, pode tentar outra vez.',GETDATE(),GETDATE(),4)
INSERT INTO Mensagem_Dominio VALUES (17,'Pode continuar tentando....',GETDATE(),GETDATE(),4)
INSERT INTO Mensagem_Dominio VALUES (17,'Estou aqui para ajudar, mas desse vez não entendi direito, o que precisa ...',GETDATE(),GETDATE(),4)
INSERT INTO Mensagem_Dominio VALUES (15,'yes',GETDATE(),GETDATE(),9)
INSERT INTO Mensagem_Dominio VALUES (15,'y',GETDATE(),GETDATE(),9)
INSERT INTO Mensagem_Dominio VALUES (15,'of course',GETDATE(),GETDATE(),9)
INSERT INTO Mensagem_Dominio VALUES (18,'{nome}, não podemos prosseguir com a sua pesquisa. Volte novamente quando mudar de ideia. E aceite os termos de uso.(S/N)',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (19,'Eu sou o @FATEC_Helper, fui criado pelos Alunos do 3º Semestre de ADS de 2020. Meu objetivo é auxiliar você a realizar seu PTG de maneira simples, tirando suas dúvidas em relação as normas e estrutura, além de informar sobre um acervo de PTG existentes. Sempre que uma perguntar aparecer e você encontrar (S/N), utilize-o como respostas. O restante das perguntas é você quem decide a melhor resposta.',GETDATE(),GETDATE(),5)
INSERT INTO Mensagem_Dominio VALUES (20,'Seu registro foi resetado.',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (21,'Você ainda não está registrado.',GETDATE(),GETDATE(),1)
INSERT INTO Mensagem_Dominio VALUES (15,'isso',GETDATE(),GETDATE(),9)

SELECT * FROM Mensagem_Dominio 


